# Generated by Django 5.0.6 on 2024-05-20 22:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 20, 22, 45, 19, 751656, tzinfo=datetime.timezone.utc), verbose_name='Дата добавления вопроса'),
        ),
    ]
