# Generated by Django 5.0.6 on 2024-05-23 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0020_remove_question_date_alter_coupon_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 23, 17, 3, 11, 962290, tzinfo=datetime.timezone.utc), verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 23, 17, 3, 11, 962290, tzinfo=datetime.timezone.utc), verbose_name='Дата добавления отзыва'),
        ),
    ]
