# Generated by Django 5.0.6 on 2024-09-08 18:14

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0026_partner_description_alter_coupon_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(max_length=2000, verbose_name='О компании')),
                ('video', models.FileField(null=True, upload_to='main_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('logo', models.ImageField(blank=True, null=True, upload_to='main_images/', verbose_name='Логотип')),
                ('history', models.TextField(max_length=2000, verbose_name='История по годам')),
                ('props', models.TextField(max_length=2000, verbose_name='Реквизиты')),
                ('certificate', models.ImageField(blank=True, null=True, upload_to='main_images/', verbose_name='Сертификат')),
            ],
            options={
                'verbose_name': 'О компании',
                'verbose_name_plural': 'О компаниях',
            },
        ),
        migrations.AlterField(
            model_name='coupon',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 9, 8, 18, 14, 3, 19980, tzinfo=datetime.timezone.utc), verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 9, 8, 18, 14, 3, 18456, tzinfo=datetime.timezone.utc), verbose_name='Дата добавления вопроса'),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 18, 14, 3, 19455, tzinfo=datetime.timezone.utc), verbose_name='Дата добавления отзыва'),
        ),
    ]
