# Generated by Django 5.0.6 on 2024-05-22 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_remove_products_quantity_alter_order_date_order_and_more'),
        ('users', '0005_remove_master_specialization_delete_specializations'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='masters',
            field=models.ManyToManyField(related_name='masters', to='users.master'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_order',
            field=models.DateField(default=datetime.datetime(2024, 5, 22, 21, 25, 50, 521779, tzinfo=datetime.timezone.utc), verbose_name='Дата заказа'),
        ),
    ]
