# Generated by Django 5.0.6 on 2024-09-08 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0018_alter_order_date_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_order',
            field=models.DateField(default=datetime.datetime(2024, 9, 8, 17, 4, 40, 647759, tzinfo=datetime.timezone.utc), verbose_name='Дата заказа'),
        ),
    ]
