# Generated by Django 5.0.6 on 2024-05-22 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_order',
            field=models.DateField(default=datetime.datetime(2024, 5, 22, 20, 43, 14, 233115, tzinfo=datetime.timezone.utc), verbose_name='Дата заказа'),
        ),
    ]
