# Generated by Django 5.0.6 on 2024-05-22 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_master_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='specialization',
        ),
        migrations.DeleteModel(
            name='Specializations',
        ),
    ]
