# Generated by Django 5.0.6 on 2024-05-21 21:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_question_delete_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200, verbose_name='Должность')),
                ('salary', models.PositiveIntegerField(default=0, verbose_name='Заработная плата')),
                ('some_info', models.TextField(max_length=1000, verbose_name='Описание должности')),
                ('city', models.CharField(max_length=30, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 21, 21, 54, 8, 440309, tzinfo=datetime.timezone.utc), verbose_name='Дата добавления вопроса'),
        ),
    ]
