# Generated by Django 5.0.6 on 2024-05-22 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0015_alter_coupon_date_alter_question_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 22, 21, 25, 50, 520779, tzinfo=datetime.timezone.utc), verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 22, 21, 25, 50, 519786, tzinfo=datetime.timezone.utc), verbose_name='Дата добавления вопроса'),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 22, 21, 25, 50, 520779, tzinfo=datetime.timezone.utc), verbose_name='Дата добавления отзыва'),
        ),
    ]
