# Generated by Django 5.0.6 on 2024-05-23 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0021_alter_coupon_date_alter_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 23, 17, 7, 24, 440378, tzinfo=datetime.timezone.utc), verbose_name='Дата добавления вопроса'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 23, 17, 7, 24, 440378, tzinfo=datetime.timezone.utc), verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 23, 17, 7, 24, 440378, tzinfo=datetime.timezone.utc), verbose_name='Дата добавления отзыва'),
        ),
    ]
