# Generated by Django 5.0.6 on 2024-05-22 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_specializations_user_is_master_master'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='user',
        ),
    ]
