# Generated by Django 5.0.6 on 2024-05-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('some_info', models.TextField(max_length=1000, verbose_name='Краткая информация')),
                ('text', models.TextField(max_length=2000, verbose_name='Текст новости')),
                ('image', models.ImageField(blank=True, null=True, upload_to='medicines_images/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
