# Generated by Django 5.0.6 on 2024-05-20 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=2000, unique=True, verbose_name='Вопрос')),
                ('answer', models.TextField(blank=True, default='На этот вопрос пока нет ответа.', max_length=2000, null=True, verbose_name='Ответ')),
                ('date', models.DateField(default=datetime.datetime(2024, 5, 20, 22, 30, 7, 464192, tzinfo=datetime.timezone.utc), verbose_name='Дата добавления вопроса')),
            ],
            options={
                'verbose_name': 'Вопрос-ответ',
                'verbose_name_plural': 'Вопросы-ответы',
            },
        ),
    ]
