# Generated by Django 5.0.6 on 2024-05-21 22:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0007_alter_question_date_alter_review_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='grade',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 21, 22, 59, 37, 397030, tzinfo=datetime.timezone.utc), verbose_name='Дата добавления вопроса'),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 21, 22, 59, 37, 397030, tzinfo=datetime.timezone.utc), verbose_name='Дата добавления отзыва'),
        ),
    ]
