# Generated by Django 5.0.6 on 2024-05-22 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0010_alter_question_date_alter_review_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField(default=datetime.datetime(2024, 5, 22, 16, 10, 1, 205740, tzinfo=datetime.timezone.utc), verbose_name='Дата окончания')),
                ('some_info', models.TextField(max_length=1000, verbose_name='Описание акции')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='Скидка в %')),
            ],
            options={
                'verbose_name': 'Купон',
                'verbose_name_plural': 'Купоны',
            },
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 22, 16, 10, 1, 204739, tzinfo=datetime.timezone.utc), verbose_name='Дата добавления вопроса'),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 22, 16, 10, 1, 205740, tzinfo=datetime.timezone.utc), verbose_name='Дата добавления отзыва'),
        ),
    ]
