# Generated by Django 5.0.6 on 2024-05-22 18:20

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_alter_products_options_alter_products_discount'),
        ('main_page', '0012_alter_coupon_date_alter_question_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_order', models.DateField(default=datetime.datetime(2024, 5, 22, 18, 20, 39, 594915, tzinfo=datetime.timezone.utc), verbose_name='Дата заказа')),
                ('date_release', models.DateField(blank=True, verbose_name='Дата отдачи заказа')),
                ('is_released', models.BooleanField(default=False)),
                ('is_processing', models.BooleanField(default=True)),
                ('is_canceled', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Комментарий')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main_page.coupon', verbose_name='Купон')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Мастер', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.products', verbose_name='Услуга')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Заказчик', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'order',
            },
        ),
    ]
