# Generated by Django 5.0.6 on 2024-05-22 21:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_alter_order_date_order'),
        ('users', '0005_remove_master_specialization_delete_specializations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='order',
            name='date_order',
            field=models.DateField(default=datetime.datetime(2024, 5, 22, 21, 23, 15, 63688, tzinfo=datetime.timezone.utc), verbose_name='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Мастер', to='users.master'),
        ),
    ]
